"""
Cross-dataset generalizability validator.
Loads a trained DQN refactoring agent and runs it on the MLCQ test split.
Outputs results to data/results/mlcq_generalization.json.
"""
import os
import sys
import json
import logging
import torch
import pandas as pd
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.utils import setup_logger, get_device, CheckpointManager
from src.data import SmellDataset, PATTERN_CLASSES
from src.models import SmellDetectionAgent
from src.evaluation import classification_report_dict, SMELL_TO_PATTERN_DOMINANT

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(name)s | %(levelname)s | %(message)s")
log = logging.getLogger("SmellRL.cross_val")

def load_config(path: str) -> dict:
    import yaml
    with open(path) as f:
        return yaml.safe_load(f)

def main():
    cfg = load_config("config.yaml")
    device = get_device(cfg.get("device", "auto"))

    # Load MLCQ test .pt file
    proc_dir = cfg["paths"]["processed_dir"]
    # We expect MLCQ pt splits to be generated by legacy preprocess if available,
    # or we can parse MLCQ CSV if cached parseable file exists.
    # To keep it completely fail-loud and robust:
    mlcq_pt_path = os.path.join(proc_dir, "test_mlcq.pt")
    if not os.path.exists(mlcq_pt_path):
        # Fail loud! No silent fallback.
        raise FileNotFoundError(
            f"MLCQ test graph cache not found at: {mlcq_pt_path}. "
            "Please ensure MLCQ dataset test graphs are preprocessed first."
        )

    log.info(f"Loading MLCQ test dataset from {mlcq_pt_path}...")
    mlcq_ds = SmellDataset.load(mlcq_pt_path)
    log.info(f"Loaded {len(mlcq_ds)} MLCQ test graphs.")

    # Load trained DQN agent
    feature_dim = mlcq_ds[0]["x"].shape[1] if len(mlcq_ds) > 0 else 783
    agent = SmellDetectionAgent(cfg, feature_dim, device)

    ckpt_mgr = CheckpointManager(cfg["paths"]["checkpoint_dir"], "smellrl_dqn", log)
    payload = ckpt_mgr.load_latest()
    if not payload:
        raise FileNotFoundError("Trained SmellRL DQN checkpoint not found.")
    
    agent.load_state_dict(payload["models"]["agent"])
    log.info("Successfully loaded trained agent from smellrl_dqn checkpoint.")

    agent.eval()
    preds = []
    true_y = []
    
    log.info("Running inference on MLCQ test dataset...")
    for item in mlcq_ds:
        true_smell = int(item["y"].item())
        true_y.append(SMELL_TO_PATTERN_DOMINANT[true_smell])
        
        action, _ = agent.select_action(item, epsilon=0.0)
        preds.append(action)

    report = classification_report_dict(true_y, preds, PATTERN_CLASSES)
    log.info(f"MLCQ Cross-Dataset Generalization Results:")
    log.info(f"  Accuracy:  {report['accuracy']:.4f}")
    log.info(f"  Macro F1:  {report['f1']:.4f}")
    log.info(f"  Precision: {report['precision']:.4f}")
    log.info(f"  Recall:    {report['recall']:.4f}")

    results_path = os.path.join(cfg["paths"]["results_dir"], "mlcq_generalization.json")
    with open(results_path, "w") as f:
        json.dump(report, f, indent=2)
    log.info(f"Saved generalization results report to: {results_path}")

if __name__ == "__main__":
    main()
